<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>false</CentralPackageTransitivePinningEnabled>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="AvaloniaUI.DiagnosticsSupport" Version="2.2.3" />
    <PackageVersion Include="EvilBaschdi.About.Avalonia" Version="2026.7.29.16" />
    <PackageVersion Include="EvilBaschdi.Core" Version="2026.8.21.10" />
    <PackageVersion Include="EvilBaschdi.Core.Avalonia" Version="2026.8.22.18" />
    <PackageVersion Include="EvilBaschdi.Core.DependencyInjection" Version="2026.7.14.17" />
    <PackageVersion Include="EvilBaschdi.Core.Settings" Version="2026.8.11.18" />
  </ItemGroup>
</Project>