<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>false</CentralPackageTransitivePinningEnabled>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="EvilBaschdi.About.Wpf" Version="2025.10.13.16" />
    <PackageVersion Include="EvilBaschdi.Core" Version="2025.9.16.16" />
    <PackageVersion Include="EvilBaschdi.Core.Wpf" Version="2025.10.16.16" />
    <PackageVersion Include="EvilBaschdi.Core.Settings" Version="2025.10.15.5" />
    <PackageVersion Include="MahApps.Metro.IconPacks.Material" Version="6.1.0" />
    <PackageVersion Include="WpfAnalyzers" Version="4.1.1" />
  </ItemGroup>
</Project>